apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name: app
          image: 737960873774.dkr.ecr.us-east-1.amazonaws.com/gti-app:latest
          ports:
            - containerPort: 8081
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: gti-cm
                key: spring_profiles_active
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: gti-cm
                key: spring_datasource_url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: gti-secret
                key: postgres_user
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gti-secret
                key: postgres_password