apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-pvc
  labels:
    app: gti
spec:
  storageClassName: default
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
