apiVersion: v1
kind: Secret
metadata:
  name: gti-secret
type: Opaque
data:
  postgres_password: MjcwMTk4
  postgres_user: cG9zdGdyZXM=
  pgadmin_default_email: YWRtaW5AZW1haWwuY29t
  pgadmin_default_password: YWRtaW4=
  geoserver_admin_user: YWRtaW4=
  geoserver_admin_password: YWRtaW4=
 
